/* generated by tools/build_offline.py; do not edit by hand */
const CACHE = "hspace-explainer-80b2955e35ab";
const FILES = [
  "00.html",
  "01.html",
  "02.html",
  "03.html",
  "04.html",
  "05.html",
  "06.html",
  "07.html",
  "08.html",
  "09.html",
  "10.html",
  "11.html",
  "12.html",
  "13.html",
  "14.html",
  "15.html",
  "assets/glossary.js",
  "assets/hspace_numbers.js",
  "assets/icon-180.png",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/katex/auto-render.min.js",
  "assets/katex/fonts/KaTeX_AMS-Regular.woff2",
  "assets/katex/fonts/KaTeX_Caligraphic-Bold.woff2",
  "assets/katex/fonts/KaTeX_Caligraphic-Regular.woff2",
  "assets/katex/fonts/KaTeX_Fraktur-Bold.woff2",
  "assets/katex/fonts/KaTeX_Fraktur-Regular.woff2",
  "assets/katex/fonts/KaTeX_Main-Bold.woff2",
  "assets/katex/fonts/KaTeX_Main-BoldItalic.woff2",
  "assets/katex/fonts/KaTeX_Main-Italic.woff2",
  "assets/katex/fonts/KaTeX_Main-Regular.woff2",
  "assets/katex/fonts/KaTeX_Math-BoldItalic.woff2",
  "assets/katex/fonts/KaTeX_Math-Italic.woff2",
  "assets/katex/fonts/KaTeX_SansSerif-Bold.woff2",
  "assets/katex/fonts/KaTeX_SansSerif-Italic.woff2",
  "assets/katex/fonts/KaTeX_SansSerif-Regular.woff2",
  "assets/katex/fonts/KaTeX_Script-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size1-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size2-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size3-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size4-Regular.woff2",
  "assets/katex/fonts/KaTeX_Typewriter-Regular.woff2",
  "assets/katex/katex.min.css",
  "assets/katex/katex.min.js",
  "assets/sim.js",
  "assets/site.js",
  "assets/style.css",
  "glossary.html",
  "index.html",
  "manifest.webmanifest"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      /* one at a time, so a single slow file cannot fail the whole install */
      for (const f of FILES) {
        try { await cache.add(new Request(f, { cache: "reload" })); } catch (e) { /* retried on next visit */ }
      }
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith("hspace-explainer-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) return hit;
      try {
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      } catch (e) {
        if (req.mode === "navigate") {
          const home = await cache.match("index.html");
          if (home) return home;
        }
        throw e;
      }
    })
  );
});

self.addEventListener("message", (event) => {
  if (!event.data || event.data.type !== "status") return;
  caches.open(CACHE).then((cache) => cache.keys()).then((keys) => {
    const base = new URL(self.registration.scope).pathname;
    const n = keys.map((r) => new URL(r.url).pathname.slice(base.length)).filter((p) => FILES.includes(p)).length;
    event.source.postMessage({ type: "status", cached: n, total: FILES.length, version: "80b2955e35ab" });
  });
});
