"""Make the site work offline after one visit.

1. Writes sw.js: a service worker that, on first load, downloads every page and asset
   into the browser cache, then serves them from the cache (so no internet is needed).
   The cache name includes a hash of all files, so a new deploy replaces the old copy.
2. Makes sure every HTML page links the web-app manifest and the home-screen icon.

Run from the explainer folder, after every content change:  python tools/build_offline.py
"""
import hashlib
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SKIP_DIRS = {"tools", ".vercel", os.path.join("assets", "glossary")}
SKIP_FILES = {"AUTHORING.md", "README.md", "vercel.json", ".vercelignore", "sw.js"}

IOS_TAGS = (
    '<meta name="apple-mobile-web-app-capable" content="yes">\n'
    '<meta name="mobile-web-app-capable" content="yes">\n'
    '<meta name="apple-mobile-web-app-status-bar-style" content="default">\n'
    '<meta name="apple-mobile-web-app-title" content="H-space">\n'
)

HEAD_TAGS = (
    '<link rel="manifest" href="manifest.webmanifest">\n'
    '<link rel="apple-touch-icon" href="assets/icon-180.png">\n'
    '<link rel="icon" type="image/png" sizes="192x192" href="assets/icon-192.png">\n'
    '<meta name="theme-color" content="#ffffff">\n'
    + IOS_TAGS
)


def site_files():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        rel_dir = os.path.relpath(dirpath, ROOT)
        dirnames[:] = [d for d in dirnames if os.path.normpath(os.path.join(rel_dir, d)) not in SKIP_DIRS and not d.startswith(".")]
        for fn in filenames:
            rel = os.path.normpath(os.path.join(rel_dir, fn))
            if rel in SKIP_FILES or fn.startswith("."):
                continue
            out.append(rel.replace(os.sep, "/"))
    return sorted(out)


def inject_head_tags():
    changed = 0
    for fn in sorted(os.listdir(ROOT)):
        if not fn.endswith(".html"):
            continue
        path = os.path.join(ROOT, fn)
        with open(path, encoding="utf-8") as f:
            html = f.read()
        if 'apple-mobile-web-app-title' in html:
            continue
        if 'rel="manifest"' in html:
            new = html.replace('<meta name="theme-color" content="#ffffff">\n', '<meta name="theme-color" content="#ffffff">\n' + IOS_TAGS, 1)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(new)
            changed += 1
            continue
        new = re.sub(r"(<link rel=\"stylesheet\" href=\"assets/style.css\">\n)", r"\1" + HEAD_TAGS, html, count=1)
        if new == html:
            new = html.replace("</head>", HEAD_TAGS + "</head>", 1)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)
        changed += 1
    return changed


SW = """/* generated by tools/build_offline.py; do not edit by hand */
const CACHE = "hspace-explainer-%(version)s";
const FILES = %(files)s;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      /* one at a time, so a single slow file cannot fail the whole install */
      for (const f of FILES) {
        try { await cache.add(new Request(f, { cache: "reload" })); } catch (e) { /* retried on next visit */ }
      }
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith("hspace-explainer-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) return hit;
      try {
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      } catch (e) {
        if (req.mode === "navigate") {
          const home = await cache.match("index.html");
          if (home) return home;
        }
        throw e;
      }
    })
  );
});

self.addEventListener("message", (event) => {
  if (!event.data || event.data.type !== "status") return;
  caches.open(CACHE).then((cache) => cache.keys()).then((keys) => {
    const base = new URL(self.registration.scope).pathname;
    const n = keys.map((r) => new URL(r.url).pathname.slice(base.length)).filter((p) => FILES.includes(p)).length;
    event.source.postMessage({ type: "status", cached: n, total: FILES.length, version: "%(version)s" });
  });
});
"""


def main():
    n_inj = inject_head_tags()
    files = site_files()
    h = hashlib.sha256()
    for f in files:
        with open(os.path.join(ROOT, f), "rb") as fh:
            h.update(f.encode())
            h.update(fh.read())
    version = h.hexdigest()[:12]
    listing = "[\n" + ",\n".join('  "%s"' % f for f in files) + "\n]"
    with open(os.path.join(ROOT, "sw.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write(SW % {"version": version, "files": listing})
    size = sum(os.path.getsize(os.path.join(ROOT, f)) for f in files)
    print(f"sw.js: {len(files)} files, {size / 1024:.0f} KB, cache version {version}; head tags added to {n_inj} page(s)")


if __name__ == "__main__":
    main()
