"""Merge glossary fragments into assets/glossary.js.

Sources: assets/glossary/core.json, then assets/glossary/L*.json in name order.
Each file maps key -> {"t": shown term, "a": [aliases], "l": level, "d": definition (plain text, light HTML ok)}.
A key or alias that is already taken is reported and skipped, so the first definition wins.

Run from the explainer folder:  python tools/build_glossary.py
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "assets", "glossary")
OUT = os.path.join(ROOT, "assets", "glossary.js")


def main():
    files = [os.path.join(SRC, "core.json")] + sorted(glob.glob(os.path.join(SRC, "L*.json")))
    merged, owner, problems = {}, {}, []
    for path in files:
        name = os.path.basename(path)
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        for key, e in data.items():
            if not isinstance(e, dict) or "d" not in e:
                problems.append(f"{name}: {key}: missing definition 'd'")
                continue
            if key in merged:
                problems.append(f"{name}: key '{key}' already defined in {owner[key.lower()]}; skipped")
                continue
            forms = [e.get("t", key)] + list(e.get("a", []))
            clean = []
            for form in forms:
                lf = form.lower()
                if lf in owner and owner[lf] != name + ":" + key:
                    problems.append(f"{name}: '{form}' (for '{key}') already used by {owner[lf]}; alias dropped")
                    continue
                owner[lf] = name + ":" + key
                clean.append(form)
            if not clean:
                continue
            entry = dict(e)
            entry["t"] = clean[0] if e.get("t", key).lower() == clean[0].lower() else e.get("t", key)
            entry["a"] = [x for x in clean if x.lower() != entry["t"].lower()]
            merged[key] = entry
            owner[key.lower()] = owner.get(key.lower(), name + ":" + key)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* generated by tools/build_glossary.py; edit assets/glossary/*.json instead */\n")
        f.write("window.GLOSSARY = ")
        json.dump(merged, f, ensure_ascii=False, indent=0)
        f.write(";\n")
    print(f"{len(merged)} terms from {len(files)} files -> assets/glossary.js")
    for p in problems:
        print("  note:", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
