"""Copy the H-space result numbers that Level 15 plots into assets/hspace_numbers.js.

Every number on Level 15 comes from this file, and every value here is read
straight from ../results/*.json, so the page can be recomputed from the raw files.

Run from the explainer folder:  python tools/extract_numbers.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RES = os.path.join(os.path.dirname(ROOT), "results")
OUT = os.path.join(ROOT, "assets", "hspace_numbers.js")


def load(name):
    with open(os.path.join(RES, name), encoding="utf-8") as f:
        return json.load(f)


def main():
    out = {"_source": "generated by explainer/tools/extract_numbers.py from results/*.json"}

    run1 = load("hspace_full.json")
    out["run1"] = {
        "_file": "results/hspace_full.json",
        "layers": {
            L: {
                "eigs_top64": d["H_eigs_top64"],
                "top25_energy_frac": d["H25_energy_frac"],
                "split_half_top25": d["split_half_overlap"],
                "H25_vs_J25_overlap": d["H25_vs_J25_overlap"],
                "random_overlap": d["random_overlap"],
                "participation_ratio": d["participation_ratio"],
                "interaction_ratio_1sigma": d["natural"]["ratio"],
            }
            for L, d in run1["layers"].items()
        },
    }

    dump = load("hs_dump_analysis_full.json")
    out["heavy_tails"] = {
        "_file": "results/hs_dump_analysis_full.json",
        "layers": {
            L: {
                "n_rows": d["loc"]["n_rows"],
                "norm_quantiles": d["loc"]["norm_quantiles"],
                "energy_share_top": d["loc"]["energy_share_top"],
                "energy_by_token_class": d["loc"]["energy_by_token_class"],
                "rows_by_token_class": d["loc"]["rows_by_token_class"],
                "split_half_from_dump": d["loc"].get("split_half_from_dump"),
            }
            for L, d in dump.items()
            if isinstance(d, dict) and "loc" in d
        },
    }

    flip5 = load("hs_flip5_full.json")
    f5 = {"_file": "results/hs_flip5_full.json", "layers": {}}
    for L, d in flip5.items():
        if not isinstance(d, dict) or "d" not in d:
            continue
        f5["layers"][L] = {}
        for est, e in d["d"].items():
            f5["layers"][L][est] = {
                "obs_lam": e["obs_lam"],
                "obs_split": e["obs_split"],
                "null_lam1_max": e["null_lam1_max"],
                "null_split3_max": e["null_split3_max"],
                "p_lam1": e["p_lam1"],
                "p_split3": e["p_split3"],
            }
        if "planted" in d:
            f5["layers"][L]["planted"] = d["planted"]
    out["flip5"] = f5

    v8 = load("hs_v8_dedup.json")
    out["v8"] = {"_file": "results/hs_v8_dedup.json", "layers": v8["layers"]}

    v8f = load("hs_v8_full.json")
    out["v8_full"] = {
        "_file": "results/hs_v8_full.json",
        "verdict": v8f.get("VERDICT_v8"),
        "n_fresh_windows": v8f.get("n_fresh_windows"),
        "layers": {
            L: {
                "screen": d["screen"],
                "punct_n_rows": d["punct"]["n_rows"],
                "punct": {
                    est: {
                        "obs_lam": e["obs_lam"],
                        "null_lam1_max": e["null_lam1_max"],
                        "obs_split": e["obs_split"],
                        "null_split3_max": e["null_split3_max"],
                    }
                    for est, e in d["punct"]["d"].items()
                },
                "planted": d["punct"]["planted"],
                "cross_run_top5_overlap": d["punct"]["cross_run_top5_overlap"],
                "random_expect_top5": d["punct"]["random_expect_top5"],
                "layer_pass": d["punct"]["layer_pass"],
            }
            for L, d in v8f["layers"].items()
        },
    }

    tw = load("c6twin5_full.json")
    out["twin5"] = {
        "_file": "results/c6twin5_full.json",
        "layers": {
            L: {
                "n_windows": d["n_windows"],
                "conds": d["conds"],
                "dS_ci95": d["dS_ci95"],
                "rank_EX_among_9": d["rank_EX_among_9"],
                "KL_EX_in_twin_range": d["KL_EX_in_twin_range"],
                "REAL": d["REAL"],
            }
            for L, d in tw["layers"].items()
        },
    }

    v9 = load("hs_v9_full.json")
    out["v9"] = {
        "_file": "results/hs_v9_full.json",
        "n_windows": {L: d["n_windows"] for L, d in v9["layers"].items()},
        "layers": {
            L: {
                "I": d["I"],
                "I_trunk": d["I_trunk"],
                "status": d.get("status"),
            }
            for L, d in v9["layers"].items()
        },
    }

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* generated by tools/extract_numbers.py from ../results/*.json; do not edit by hand */\n")
        f.write("window.HS = ")
        json.dump(out, f, indent=1)
        f.write(";\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
